### ISSUE TITLE
v5.23.0: collectPaginatedAPI/iteratePaginatedAPI no longer accept dataSources.query (start_cursor: string | null breaks PaginatedArgs constraint)

### ISSUE THREAD

**Issue by nakanoasaservice** [makenotion/notion-sdk-js#743]
## Summary

Upgrading from `v5.22.0` to `v5.23.0` breaks type checking for any code that passes `notion.dataSources.query` (and other endpoints whose `start_cursor` gained `| null`) to `collectPaginatedAPI` / `iteratePaginatedAPI`.

## Reproduction

```ts
import { Client, collectPaginatedAPI } from "@notionhq/client"

declare const notion: Client

// Compiles on v5.22.0, fails on v5.23.0
const rows = await collectPaginatedAPI(notion.dataSources.query, {
  data_source_id: "xxxx",
})
```

Error (TypeScript 5.9.3, `strict: true`):

```
error TS2345: Argument of type '(args: WithAuth<QueryDataSourceParameters>) => Promise<QueryDataSourceResponse>' is not assignable to parameter of type '(args: PaginatedArgs) => Promise<PaginatedList<PageObjectResponse | PartialPageObjectResponse | PartialDataSourceObjectResponse | DataSourceObjectResponse>>'.
  Types of parameters 'args' and 'args' are incompatible.
    Type 'PaginatedArgs' is not assignable to type 'WithAuth<QueryDataSourceParameters>'.
      Property 'data_source_id' is missing in type 'PaginatedArgs' but required in type 'QueryDataSourcePathParameters'.
```

The `data_source_id is missing` part is misleading — it is a secondary message caused by failed generic inference (see below).

## Root cause

v5.23.0 changed `start_cursor` on request parameter types from `string` to `string | null` (so `next_cursor` can be piped back directly):

```ts
// src/api-endpoints/data-sources.ts (v5.23.0)
start_cursor?: string | null
```

But the `PaginatedArgs` constraint used by the pagination helpers in `src/helpers.ts` was not updated:

```ts
type PaginatedArgs = {
  start_cursor?: string
}

export async function collectPaginatedAPI<Args extends PaginatedArgs, Item>(
  listFn: (args: Args) => Promise<PaginatedList<Item>>,
  firstPageArgs: Args
): Promise<Item[]>
```

Under `strictNullChecks`, `{ start_cursor?: string | null }` does not extend `{ start_cursor?: string }`, so `WithAuth<QueryDataSourceParameters> extends PaginatedArgs` is now false. Generic inference of `Args` falls back to the constraint (`PaginatedArgs`), producing the confusing error above.

I verified that changing the constraint to `start_cursor?: string | null` makes the exact same call compile against the v5.23.0 endpoint types.

## Suggested fix

Update the helper constraint to match the new parameter types:

```ts
type PaginatedArgs = {
  start_cursor?: string | null
}
```

The runtime already handles `null` cursors (they are stripped from the query string and JSON body as of v5.23.0), so this is a types-only fix.

## Environment

- `@notionhq/client`: 5.23.0 (works on 5.22.0)
- TypeScript: 5.9.3, `strict: true`
